proyectofarmacia/core/urls.py
from django.urls import path

# importamos las vistas basadas en clases para servir los templates
# from .views import HomePageView, SamplePageView, ArchivoPageView
from .views import HomePageView


urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    # path('sample/', SamplePageView.as_view(), name="sample"),
    # path('archivo/', ArchivoPageView.as_view(), name="archivo"),

]

proyectofarmacia/pedidos/urls.py
from django.urls import path

# el siguiente impor no es necesario en vistas basadas en clases
# from . import views

from .views import PedidoListView, PedidoDetailView, PedidoCreate, PedidosUpdate, PedidosDelete, ArchivoListView, PedidosRetirar, retirar_asincrono

pedidos_patterns = ([

    # vistas basadas en clases
    path('', PedidoListView.as_view(), name='pedidos'),
    path('archivo/', ArchivoListView.as_view(), name='archivo'),
    #path('<int:pk>/<slug:slug>/', PedidoDetailView.as_view(), name='pedido'),
    path('pedidos/<int:pk>/', PedidoDetailView.as_view(), name='pedido'),
    path('crear/', PedidoCreate.as_view(), name='crear'),
    path('procesar/<int:pk>/', PedidosUpdate.as_view(), name='procesar'),
    path('retirar/<int:pk>/', PedidosRetirar.as_view(), name='retirar'),
    path('delete/<int:pk>/', PedidosDelete.as_view(), name='delete'),
    path('<int:pk>/retirar_asinc/', retirar_asincrono, name='retirar_asinc'),

    
    # vistas basadas en funciones:
    # path('', views.pedidos, name='pedidos'),
    # path('<int:pedido_id>/<slug:pedido_slug>/', views.pedido, name='pedido'),
], 'pedidos')

proyectofarmacia/proyectofarmacia/urls.py
from django.contrib import admin
# hay que importar la funcion include
from django.urls import path, include
from pedidos.urls import pedidos_patterns

urlpatterns = [
    # se agrega un path a la raiz, con un include que cargara de la app core el fichero url
    path('', include('core.urls')),
    path('pedidos/', include(pedidos_patterns)),
    path('admin/', admin.site.urls),
    # Paths de auth
    path('accounts/', include('django.contrib.auth.urls')),
]

proyectofarmacia/pedidos/models.py
from datetime import datetime
from django.db import models


class Pedidos(models.Model):
    paciente = models.CharField(verbose_name="Paciente", max_length=200)
    cama = models.CharField(verbose_name="Cama", max_length=100)
    insumos = models.TextField(verbose_name="Insumos")
    solicitante = models.CharField(verbose_name="Solicitante", max_length=200)
    procesante = models.CharField(verbose_name="Procesante", max_length=200, blank=True)
    retirante = models.CharField(verbose_name="Retirante", max_length=200, blank=True)
    urgencia = models.CharField(verbose_name="Urgencia", max_length=100)
    estado = models.CharField(verbose_name="Estado", max_length=100, default='pendiente')
    id_modificado = models.CharField(verbose_name="modificado", max_length=50, default='no')
    
    created = models.CharField(verbose_name="Fecha de creación", max_length=100, blank=True, default=datetime.now().strftime('%d/%m/%Y %H:%M:%S'))
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
    
    fecha_procesamiento = models.CharField(verbose_name="Fecha de procesamiento", max_length=100, blank=True, default='0000')
    fecha_despachable = models.CharField(verbose_name="Fecha despachable", max_length=100, blank=True, default='0000')
    fecha_despacho = models.CharField(verbose_name="Fecha de despacho", max_length=100, blank=True, default='0000')

    class Meta:
        verbose_name = "pedido"
        verbose_name_plural = "pedidos"
        # la siguiente linea le inciacomo se presentan los resultados, segun la urgencia y al momento de creacion
        ordering = ['-urgencia', 'created']

    def __str__(self):
        return self.insumos

    # metodo para dividir el string de insumos
    def insumos_as_list(self):
        return self.insumos.split(';')
    
    # metodo para actualizar la fecha
    #def actualizar_fecha(self):
        #return self.insumos.split(';')

proyectofarmacia/pedidos/views.py
# la siguiente linea es necesaria para las vistas basadas en clases
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import redirect, get_object_or_404

# el siguiente import no es necesario en vistas basadas en clases
#from django.shortcuts import render, get_object_or_404, get_list_or_404

from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.http import JsonResponse, Http404
from datetime import datetime

from .models import Pedidos
from pacientes.models import Paciente
from insumos.models import Insumo


class StaffRequiredMixin(object):
    """
    Este mixin requerira que el usuario sea miembro del staff
    """

    @method_decorator(staff_member_required)
    def dispatch(self, request, *args, **kwargs):
        # if not request.user.is_staff:
        #     return redirect(reverse_lazy('admin:login'))
        return super(StaffRequiredMixin, self).dispatch(request, *args, **kwargs)


# vistas basadoas en clases:
class PedidoListView(ListView):
    model = Pedidos

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(reverse_lazy('login'))

        return super(PedidoListView, self).dispatch(request, *args, **kwargs)


# vista de archivo
class ArchivoListView(ListView):
    model = Pedidos
    template_name_suffix = '_archivo'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(reverse_lazy('login'))
        
        return super(ArchivoListView, self).dispatch(request, *args, **kwargs)



class PedidoDetailView(DetailView):
    model = Pedidos
    

#@method_decorator(staff_member_required, name='dispatch')
class PedidoCreate(CreateView):
    model = Pedidos
    # en la siguiente lines se tienen que especificar los campos que el usuario podra crear
    fields = ['created','paciente','cama','insumos','urgencia']
    # success_url = reverse_lazy('pedidos:pedidos')

    ###################################################
    # MANDo EL CONTEXT DATA
    def get_context_data(self, **kwargs):
        context = super(PedidoCreate, self).get_context_data(**kwargs)
        context['pacientes'] = Paciente.objects.all()
        context['insumos'] = Insumo.objects.all()
        context['fecha_de_creacion'] = datetime.now().strftime('%d/%m/%Y %H:%M:%S')
        return context
    ###################################################


    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if 'sala' in request.user.groups.values_list('name', flat=True):
                return super(PedidoCreate, self).dispatch(request, *args, **kwargs)
            else:
                return redirect(reverse_lazy('home') + '?solo_para_usuarios_de_sala')
        else:
            return redirect(reverse_lazy('login') + '?debe_autentificarse_para_poder_acceder')


    def get_success_url(self):
        #return reverse_lazy('pedidos:procesar', args=[self.object.id]) + '?ok'
        return reverse_lazy('pedidos:crear') + '?creado'

    ########################################
    # VALIDAR FORMULARIOS
    #x = datetime.datetime.now()
    #fecha = x.strftime("%d-%m-%Y %H:%M:%S")
    def form_valid(self, form):
        #print(self.request.method)
        #print( self.request.user.username)
        if self.request.user.get_full_name():
            form.instance.solicitante = self.request.user.get_full_name()
        else:
            form.instance.solicitante = self.request.user.username
        #form.instance.solicitante = self.request.user.username
        return super().form_valid(form)
    ########################################


##############################
#       PROCESAR PEDIDO
##############################
class PedidosUpdate(UpdateView):
    model = Pedidos
    #fields = ['procesante','estado','fecha_procesamiento','fecha_despachable']
    fields = ['estado','fecha_procesamiento']
    template_name_suffix = '_update_form'
    
    ###################################################
    # MANDo UN CONTEXT DATA
    def get_context_data(self, **kwargs):
        context = super(PedidosUpdate, self).get_context_data(**kwargs)
        context['fecha_procesamiento'] = datetime.now().strftime('%d/%m/%Y %H:%M:%S')
        return context
    ###################################################

    #success_url = reverse_lazy('pedidos:procesar')
    def get_success_url(self):
        #return reverse_lazy('pedidos:procesar', args=[self.object.id]) + '?ok'
        return reverse_lazy('pedidos:pedidos') + '?procesado'
    

    def dispatch(self, request, *args, **kwargs):
        
        if request.user.is_authenticated:
            if 'farmacia' in request.user.groups.values_list('name', flat=True):
                return super(PedidosUpdate, self).dispatch(request, *args, **kwargs)
            else:
                return redirect(reverse_lazy('home') + '?solo_para_usuarios_de_farmacia')
        else:
            return redirect(reverse_lazy('login') + '?debe_autentificarse_para_poder_acceder')
        
        # if not request.user.is_authenticated:
        #     return redirect(reverse_lazy('login'))
        # return super(PedidosUpdate, self).dispatch(request, *args, **kwargs)


    ########################################
    # VALIDAR FORMULARIOS
    def form_valid(self, form):
        if self.request.user.get_full_name():
            form.instance.procesante = self.request.user.get_full_name()
        else:
            form.instance.procesante = self.request.user.username
        x = datetime.now()
        form.instance.fecha_despachable = x.strftime('%d/%m/%Y %H:%M:%S')
        #print(self.request.user.username)
        return super().form_valid(form)
    ########################################



##############################
#       RETIRAR PEDIDO       #
##############################
class PedidosRetirar(UpdateView):
    model = Pedidos
    #fields = ['procesante','estado','fecha_procesamiento','fecha_despachable']
    fields = ['retirante','estado','fecha_despacho']
    template_name_suffix = '_retirar'
    
    #success_url = reverse_lazy('pedidos:procesar')
    def get_success_url(self):
        #return reverse_lazy('pedidos:procesar', args=[self.object.id]) + '?ok'
        return reverse_lazy('pedidos:pedidos') + '?retirado'
    

    def dispatch(self, request, *args, **kwargs):
        
        if request.user.is_authenticated:
            if 'sala' in request.user.groups.values_list('name', flat=True):
                return super(PedidosRetirar, self).dispatch(request, *args, **kwargs)
            else:
                return redirect(reverse_lazy('home') + '?solo_para_usuarios_de_sala')
        else:
            return redirect(reverse_lazy('login') + '?debe_autentificarse_para_poder_acceder')
        
        # if not request.user.is_authenticated:
        #     return redirect(reverse_lazy('login'))
        # return super(PedidosUpdate, self).dispatch(request, *args, **kwargs)


    ########################################
    # VALIDAR FORMULARIOS
    def form_valid(self, form):
        if self.request.user.get_full_name():
            form.instance.retirante = self.request.user.get_full_name()
        else:
            form.instance.retirante = self.request.user.username
        #imprime la etiqueta de 'retirado' en el estado del pedido
        
        x = datetime.now()
        form.instance.fecha_despacho = x.strftime('%d/%m/%Y %H:%M:%S')
        
        form.instance.estado = 'retirado'
        #print(self.request.user.username)
        return super().form_valid(form)
    ########################################




class PedidosDelete(DeleteView):
    model = Pedidos
    #success_url = reverse_lazy('pedidos:pedidos')

    def get_success_url(self):
        return reverse_lazy('pedidos:pedidos') + '?borrado'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(reverse_lazy('login'))
        return super(PedidosDelete, self).dispatch(request, *args, **kwargs)


# vistas basadas en funciones:
# def pedidos(request):
#     pedidos = get_list_or_404(Pedidos)
#     return render(request, 'pedidos/pedido_list.html', {'pedidos':pedidos})


# def pedido(request, pedido_id, pedido_slug):
#     pedido = get_object_or_404(Pedidos, id=pedido_id)
#     return render(request, 'pedidos/pedidos_detail.html', {'pedido':pedido})


#vista para retirar pedidos de forma asincrona
def retirar_asincrono(request, pk):
    
    #print("llego la peticion para retirar el id ",pk)
    respuesta = 'se intenta retirar el pedido '+str(pk)
    
    x = datetime.now()
    fecha_despacho = x.strftime('%d/%m/%Y %H:%M:%S')
    #fecha_despacho = str(datetime.now())[:-7]

    if request.user.is_authenticated:
        #print("el pasiente es: ", pedido.paciente)
        retirante = ''
        if request.user.get_full_name():
            retirante = request.user.get_full_name()
        else:
            retirante = request.user.username
        
        print('el retirante es ',retirante)
        
        #primer metodo para actualizar ma base de datos
        #pedido = get_object_or_404(Pedidos, pk=pk)
        #pedido.estado = 'retirado'
        #pedido.save()

        #segundo metodo para actualizar la base de datos
        pedido = Pedidos.objects.filter(id=pk).update(estado='retirado', retirante=retirante, fecha_despacho=fecha_despacho)


        respuesta = 'la pedido '+str(pk)+' fue retirado con exito'
    else:
        raise Http404("El usuario no esta identificado")
    
    return JsonResponse({'respuesta':respuesta})

proyectofarmacia/pedidos/templates/pedidos/pedidos_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Borrar pedido{% endblock %}
{% block content %}
{% comment %} {% include 'pedidos/includes/pedidos_menu.html'%} {% endcomment %}
<main role="main">
  <div class="container">
    <div class="row mt-3">

      <div class="mx-auto alert alert-danger text-center" role="alert">
        <form action="" method="post">{% csrf_token %}
          <p><i class="fa fa-warning ml-1 fa-4x"></i></p>
          <p>¿Estás seguro de que quieres borrar el pedido?</p>
          <p>ID {{object.id }}</p>
          <p>{{object.cama}} - {{ object.paciente }}</p>
          <p>{{object.created}}</p>
          <p><input class="btn btn-danger" type="submit" value="Sí, borrar." /></p>
        </form>
      </div>

    </div>
  </div>
</main>
{% endblock %}

proyectofarmacia/pedidos/templates/pedidos/pedidos_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Crear pedido{% endblock %}
{% block content %}
{% comment %} {% include 'pedidos/includes/pedidos_menu.html'%} {% endcomment %}

<main role="main">
  <div class="container pt-2">

    {% comment %}
    Mensaje de confirmacion por una edicion exitosa
    {% endcomment %}
    {% if 'creado' in request.GET %}
      <div class="alert alert-success alert-dismissible fade show desvanecer" role="alert">
        El pedido fue creado correctamente.
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endif %}


    {% comment %} <div class="row mt-3 mb-3">
      <div class="col-md-9 mx-auto"> {% endcomment %}

    <div class="card borde-superior-azul" >
      <header class="pt-2 pb-1 bg-gris-muy-claro">
        <h4 class="text-center text-gris-oscuro">Crear pedido</h4>
      </header>
        
      <form action="" method="post" id="formularioCrear" onsubmit="return enviar()">{% csrf_token %}
        <div class="pedidos-panel-colapsable p-3">

        <input type="hidden" class="" name="created" required value="{{fecha_de_creacion}}">

          {% comment %} 
          BOTON URGENCIA
          {% endcomment %}
          <div class="form-group text-center mb-2">
            <div class="btn-group btn-group-toggle mx-auto" data-toggle="buttons">
              <label class="btn btn-outline-warning" for="id_urgencia">
                <input type="radio" name="urgencia" id="id_urgencia" autocomplete="off" value="urgente"> Urgente
              </label>
              <label class="btn btn-outline-success active" for="id_urgencia2">
                <input type="radio" name="urgencia" id="id_urgencia2" autocomplete="off" value="no urgente" checked> No urgente
              </label>
            </div>
          </div>


          {% comment %}
          INPUT PACIENTE
          {% endcomment %}
          <div class="form-group text-center mt-4">
            {% comment %} <label class="" for="select_nombre">Paciente:</label> {% endcomment %}
            <select class="form-control mx-auto" id="select_nombre" onchange="set_nombre_y_cama();" required>
              <option value="" selected>Selecciona un paciente</option>
              {% for paciente in pacientes|dictsort:"cama" %}
              <option value="{{paciente}}">{{paciente}}</option>
              {% endfor %}
            </select>
          
            <input type="hidden" class="" name="paciente" required id="id_paciente">
            <input type="hidden" class="" name="cama" maxlength="100" required id="id_cama">

          </div>



            {% comment %}
            TABLA INSUMOS
            {% endcomment %}
            <div class="form-group text-center mt-4">
            
              <table class="tabla" id="tabla_insumos">
  
                <tr class="text-center text-gris-oscuro">
                  <th width="75%">insumo</th>
                  <th width="10%">cantidad</th>
                  <th width="14%">opciones</th>
                </tr>

                {% comment %} <tr>
                  <td class='insumo'></td>
                  <td class='cantidad'>100</td>
                  <td>
                    <i class='fa fa-plus fa-lg mx-2' onclick='sumar(this)'></i>
                    <i class='fa fa-minus fa-lg mx-2' onclick='restar(this)'></i>
                    <i class='fa fa-remove fa-lg mx-2' onclick='quitar(this)'></i>
                  </td>
                </tr> {% endcomment %}
              </table>

              <select class="form-control mx-auto" id="select_insumo" onchange="set_insumos()">
                <option value="" selected>Selecciona los insumos</option>
                {% for insumo in insumos %}
                <option value="{{insumo}}">{{insumo}}</option>
                {% endfor %}
              </select>

              <input type="hidden" class="" name="insumos" required id="id_insumos" readonly>

            </div>
          


            <div class="text-center mt-4">
              <input type="submit" class="btn btn-outline-gris btn-block mx-auto" style="width:50%;" value="Crear pedido" onsubmit="return enviar()"/>
            </div>


            {% comment %} <button class='btn btn-sm btn-primary btn-block' onclick="enviar()">nuevo boton Enviar</button> {% endcomment %}
  
            {% comment %} <div id="lista"></div> {% endcomment %}



          </div>
        </form>

<script>

function set_nombre_y_cama(){
  var seleccionado = document.getElementById("select_nombre").value;
  //console.log(seleccionado);
  //console.log(seleccionado.slice(0,5));
  //console.log(seleccionado.slice(8,seleccionado.length));
  if(seleccionado != ''){
    var cama = seleccionado.slice(0,5);
    var nombre = seleccionado.slice(8,seleccionado.length);

    document.getElementById("id_paciente").value = nombre;
    document.getElementById("id_cama").value = cama;

  }else{
    confirm('no selecciono ningun paciente');
  }
  

}


function set_insumos(){
  var seleccionado = document.getElementById("select_insumo").value;
  console.log(seleccionado);

  if(seleccionado != ""){
    var tabla_insumos = document.getElementById("tabla_insumos");
    tabla_insumos.innerHTML += "<tr class=''><td class='insumo'>" + seleccionado + "</td><td class='cantidad'>1</td><td><span class='btn btn-sm btn-outline-gris mr-1 mb-1' onclick='sumar(this)'><i class='fa fa-plus fa-lg'></i></span><span class='btn btn-sm btn-outline-gris mr-1 mb-1' onclick='restar(this)'><i class='fa fa-minus fa-lg'></i></span><span class='btn btn-sm btn-outline-gris mr-1 mb-1' onclick='quitar(this)'><i class='fa fa-trash-o fa-lg'></i></span></td></tr>";   
    //tabla_insumos.innerHTML += "<tr class=''><td class='insumo'>" + seleccionado + "</td><td class='cantidad'>1</td><td><i class='fa fa-plus fa-lg mr-1 mb-1' onclick='sumar(this)'></i><i class='fa fa-minus fa-lg mr-1 mb-1' onclick='restar(this)'></i><i class='fa fa-trash-o fa-lg mr-1 mb-1' onclick='quitar(this)'></i></td></tr>";   
  }else{
    //console.log("no selecciono ningun insumo");
  }


}


function enviar(){
  //var lista = document.getElementById("lista");
  var insumos = document.getElementsByClassName("insumo");
  var cantidad = document.getElementsByClassName("cantidad");
  //console.log(insumos.length);
  //alert(insumos.length)
  var texto = "";
  for(var i = 0; i<insumos.length;i++){
    //console.log(insumos[i].innerHTML);
    if(texto == ''){
      texto += insumos[i].innerHTML + " | x " + cantidad[i].innerHTML + " u.";
    }else{
      texto += ";" + insumos[i].innerHTML + " | x " + cantidad[i].innerHTML + " u.";
    }

  }

  document.getElementById("id_insumos").value = texto;

  //lista.innerHTML = texto;
  //document.getElementById("formularioCrear").submit();
  return true;
}



function restar(elemento){
  console.log("restar mundooo");
  var cantidad = parseInt(elemento.parentElement.previousElementSibling.innerHTML);
  if(cantidad > 1){
     elemento.parentElement.previousElementSibling.innerHTML = cantidad -1;
     console.log("la cantidad ya ebtro al if");
  }
  console.log("la cantidad no entro al if");
}


function sumar(elemento){
  console.log("sumar mundooo");
  console.log(parseInt(elemento.parentElement.previousElementSibling.innerHTML));
  var cantidad = parseInt(elemento.parentElement.previousElementSibling.innerHTML);
  //elemento.parentElement.previousElementSibling.innerHTML = cantidad +1;
  elemento.parentElement.previousElementSibling.innerHTML = cantidad + 1;

}



function quitar(elemento){
  //elemento.innerHTML = "siu";
  elemento.parentNode.parentNode.remove();
}


</script>





    </div>
  </div>
</main>
{% endblock %}

proyectofarmacia/pedidos/templates/pedidos/pedidos_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Procesar pedido{% endblock %}
{% block content %}
{% comment %} {% include 'pedidos/includes/pedidos_menu.html'%} {% endcomment %}
<main role="main">
  <div class="container pt-2">


    <div class="card mb-3 {% if pedidos.urgencia == 'urgente' %}color-urgente-borde{% else %}color-no-urgente-borde{% endif %}" >
      
      <header class="p-2 bg-gris-muy-claro">
        <div class="row">
          {% comment %} <a href="{% url 'pedidos:pedido' pedido.id %}" style="color:white;"> {% endcomment %}
              

          <div class="col-2">
            <span class="float-left badge-id">id {{pedidos.id}}</span>
          </div>

          <div class="col-6 text-center">
            <span class="">{{pedidos.cama}} - {{pedidos.paciente}}</span>
          </div>


          {% comment %} 
          Visualiza la urgencia del pedidos (rutina, urgente)
          {% endcomment %}
          {% comment %} <div class="col text-center">
            {% if pedidos.urgencia == 'no urgente' %}
              <span class="badge badge-success">rutina</span>
            {% elif pedidos.urgencia == 'urgente' %}
              <span class="badge badge-danger">urgente</span>
            {% else %}
              <span class="badge badge-warning">modificado</span>
            {% endif %}
          </div> {% endcomment %}


          {% comment %} 
          Visualizar el estado del pedidos (pendiente, en proceso o para retirar)
          {% endcomment %}
          <div class="col-4">
            <span class="float-right badge-estado badge-en-proceso">en proceso</span>
          </div>
            

        </div><!--final del row-->

        {% comment %} <hr class="btn-color2 m-2 p-0"> {% endcomment %}

        {% comment %}
        Visualiza la sala, la cama y el nombre del paciente
        {% endcomment %}
        {% comment %} <h6 class="text-center m-0">{{pedidos.cama}} - {{pedidos.paciente}}</h6> {% endcomment %}
            
        {% comment %} <hr class="btn-color2 m-2 p-0"> {% endcomment %}

      </header><!--final del header-->


      <form action="" method="post" onsubmit="return seteos_despachable_onsubmit()">{% csrf_token %}
      {% comment %} {{ form.as_p }} {% endcomment %}

        <div class="borde-superior-panel-colapsable p-3">
          
          <h6 class="text-center titulo-seccion">Insumos solicitados</h6>
          <div class="my-2">
            <ul class="list-group ">

              {% for insumo in pedidos.insumos_as_list %}    
                <li class="list-group-item ">
                  <div class="form-check pl-3 py-0">
                    {% comment %} los input checkbox no son usados para actualizar en la base de datos
                    solo se utiliza el aspecto visual del checkbox y para validar el boton de submit {% endcomment %}
                    <input type="checkbox" class="form-check-input" id="{{forloop.counter}}--{{insumo|slugify}}" required>
                    {% comment %} el forloop.counter y el insumo|slugify solucionan el problema de los id duplicados en el label  {% endcomment %}
                    <label class="form-check-label" for="{{forloop.counter}}--{{insumo|slugify}}">{{insumo}}</label>
                  </div>
                </li>
              {% endfor %}
            
            </ul>
          </div>
      
          {% comment %}
          django establece el siguiente input con el nombre usuario que accede
          {% endcomment %}
          {% comment %} <div class="form-group">
            <label for="id_procesante">Procesado:</label>  {% endcomment %}
            <input type="hidden" class="" name="procesante" value="{{pedidos.procesante}}" id="id_procesante" readonly>
            <input type="hidden" class="" name="fecha_procesamiento" id="id_fecha_procesamiento" value="{{fecha_procesamiento}}" readonly>
          {% comment %} </div> {% endcomment %}
      
          {% comment %} <p>
            <label for="id_procesante">Procesante:</label> 
            <input type="text" name="procesante" value="{{pedidos.procesante}}" maxlength="200" id="id_procesante" readonly>
          </p> {% endcomment %}
          

          {% comment %}
          el estado se toma de la base de datos, y javascript lo actualiza a 'para retirar' en la funcion onsubmit
          {% endcomment %}
          {% comment %} <div class="form-group">
            <label for="id_estado">Estado:</label>  {% endcomment %}
            <input type="hidden" class="" name="estado" value="{{pedidos.estado}}" required id="id_estado" readonly>
          {% comment %} </div> {% endcomment %}

          {% comment %} <p>
            <label for="id_estado">Estado:</label> 
            <input type="text" name="estado" value="{{pedidos.estado}}" maxlength="100" required id="id_estado" readonly>
          </p> {% endcomment %}
          
          

          {% comment %} <div class="form-group">
            <label for="id_fecha_despachable">Fecha despachable:</label>  
            <input type="hidden" class="" name="fecha_despachable" id="id_fecha_despachable" value="{{pedidos.fecha_despachable}}" readonly>
          </div> {% endcomment %}

          {% comment %} <p>
            <label for="id_fecha_despachable">Fecha despachable:</label> 
            <input type="text" name="fecha_despachable" id="id_fecha_despachable" value="{{pedidos.fecha_despachable}}" readonly>
          </p> {% endcomment %}



          <div class="text-center mt-4">
            <input type="submit" class="btn btn-block btn-outline-gris mx-auto" style="width:50%;" value="Procesar pedido" />
          </div>
  
        </div>
      </form>

    </div>


<script>
  function seteos_despachable_onsubmit() {
    
    //var d = new Date();
    //var fecha = d.toLocaleDateString()+' '+d.toLocaleTimeString();
    //var fecha = '{% now "DATETIME_FORMAT" %}';
    //document.getElementById("id_fecha_despachable").value = fecha;

    document.getElementById("id_estado").value = 'para retirar';
    
    //confirm("ejecutando la funcion onsubmit ;D");
  }
  
  /*================================
  SETEO DE LA FECHA DE PROCESAMIENTO
  ================================*/
  //var d = new Date();
  //var fecha = d.toLocaleDateString()+' '+d.toLocaleTimeString();
  //document.getElementById("id_fecha_procesamiento").value = fecha;

</script>


{% comment %} <div class=""> {% endcomment %}
{% comment %} {% now "DATETIME_FORMAT" %} {% endcomment %}
{% comment %} {{pedidos.created}}
</div> {% endcomment %}
          
          








  </div>
</main>
{% endblock %}